name: Build and Deploy
on:
    workflow_dispatch:
        inputs:
            subscription_id:
                description: 'Subscription ID'
                required: true
            tenant_id:
                description: 'Tenant ID'
                required: true
            client_id:
                description: 'Client ID'
                required: true
            client_secret:
                description: 'Client Secret'
                required: true

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run npm install
        run: npm install express

      - name: Docker Build the App
        run: docker build -t hello-world-app:latest .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Azure CLI Login
        run: az login --service-principal -u ${{ inputs.client_id }} -p ${{ inputs.client_secret }} --tenant ${{ inputs.tenant_id }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ inputs.subscription_id }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve -var subscription_id=${{ inputs.subscription_id }} -var tenant_id=${{ inputs.tenant_id }} -var client_id=${{ inputs.client_id }} -var client_secret=${{ inputs.client_secret }}
        working-directory: ./terraform

      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: hello-world-app:latest

      - name: Rollback Deployment
        run: kubectl rollout undo deployment/hello-world-app